# Generated by Django 2.2.1 on 2019-05-29 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190523_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='inicio',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 14, 22, 7, 157410, tzinfo=utc)),
        ),
    ]
