# Generated by Django 2.2.1 on 2019-05-29 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190529_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
